In [14]:
import numpy as np 
a = np.arange(10,60,5).reshape(2,5)
a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [2]:
import numpy as np
print(np.array([8,4,6,0,2]))

[8 4 6 0 2]


In [22]:
import numpy as np
A = np.array( [[1,2,3],[4,5,6]] )
print(A)
print(" ")

print(A[0,1],A[1,2])
print(" ")
print(A[0])

[[1 2 3]
 [4 5 6]]
 
2 6
 
[1 2 3]


# Exercise 1.1

In [28]:
import numpy as np
A = np.array( [[3,-1,4],[1,5,-9]] )
B = np.array( [[[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]]] )
np.dot(A,B)

array([[[ 19,  13, -52,   7]],

       [[-30,  21, 103,  39]]])

# Exercise 1.4:

In [34]:
import numpy as np
X = np.array( [3,-4,1] )
Y = np.array( [5,2,3] )
print(X+10)
print(Y*4)
print(X+Y)
print(X*Y)

print(X.min())
print(X.argmax())

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]
-4
0


# Part 2

In [36]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)


e:\Users\ACER\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [45]:
import numpy as np
iris_data = np.genfromtxt(R'E:\Users\ACER\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv' ,
                         delimiter = ",",skip_header=1)